# GET https://api.skypicker.com/locations

# GET https://api.skypicker.com/flights?fly_from=Istanbul&fly_to=Prague&dateFrom=18/11/2020&dateTo=19/11/2020&partner=picky&v=3

# GET https://api.skypicker.com/flights?fly_from=IST&fly_to=PRG&dateFrom=15/09/2020&partner=picky&v=3